### PR TITLE
[WIP] Update to tokio 1.16

### LINKED ISSUE #419: update to tokio 1.16
When updating to tokio 1.16, the controller test fails. It seems that the tokio testing functionality may have changed, and that it's no longer properly running multi-threaded. The controller thread spins up a telnet (and/or websocket) state machine in its own thread which then makes requests against the Goose controller: with 1.16+ it seems only one of the threads runs.

### PR DESCRIPTION
**Pull request by jeremyandrews**
- update Tokio to 1.16.1+ (fixes #419)
 - timeout Goose if controller tests fail to shut it down after 60 seconds

@TODO: Solve the issue where tests appear to not be running in threads

### CODE REVIEW

**Comment by ahmedriza** [comment]
@jeremyandrews were you able to make the Gaggle tests to work.  Also running into the locked in `tokio` version `1.15` dependency issue.  Be nice to move onto the newer `tokio` versions.

**Comment by jeremyandrews** [comment]
@ahmedriza Sorry, I missed your question somehow. I need to pick this back up again. Unfortunately it's a very non-trivial update, as I need to remove all non-async code (which is heavily used in Gaggles).

**Comment by lamalex** [comment]
I'm confused what the problem is.
The tests already hang for me on `main` without updating to a recent Tokio.

So is upgrading Tokio an actual regression?
I'd be curious to know how many of the 50 forks are just Tokio version bumps.
Goose is really great - but this old pinned tokio is an achilles heel. It basically makes it impossible to integrate with an existing project.

```
$ cargo test --features gaggle

     Running tests/controller.rs (target/debug/deps/controller-8042a651a5d002a0)

running 2 tests
test test_telnet_controller has been running for over 60 seconds
test test_websocket_controller has been running for over 60 seconds
````

**Comment by jeremyandrews** [comment]
All tests currently run successfully every time a PR is committed, so the tests are not currently broken.

If you don't need Gaggles, you'd be able to update tokio locally without problem. The underlying issue is explained in https://github.com/tag1consulting/goose/pull/420#issuecomment-1034914835 -- I have a WIP replacement that I've not had time to complete. Hopefully around new years ...

**Comment by jeremyandrews** [comment]
Possibly? In any case, I'm planning to roll a release w/o Gaggle support shortly, which should allow us to upgrade all libraries. (And then Gaggle support will be added back in a future release, when it's ready.)

**Pull request closed without merging**
