### PR TITLE
Use info not println

### PR DESCRIPTION
**Pull request by JordiPolo**
I think we are doing logging on the section and also it is good so users can control if they want to see this or not.

### CODE REVIEW

**Comment by jeremyandrews** [comment]
If you do not want the statistics displayed, the intent is that you don't invoke `.print()`.

If you invoke GooseAttack as follows, it will print the statistics:
```rust
    GooseAttack::initialize()?
        .register_taskset(taskset!("LoadtestTasks")
            .register_task(task!(loadtest_index))
        )
        .execute()?
        .print();
```

But if instead you invoke GooseAttack as follows, it will simply return the statistics to you, and you can do with them as you please:
```rust
    let goose_statistics = GooseAttack::initialize()?
        .register_taskset(taskset!("LoadtestTasks")
            .register_task(task!(loadtest_index))
        )
        .execute()?;
```

**Comment by JordiPolo** [comment]
Yes, but we may not be talking about the same thing. 
If you see the diff, there are a few `println!` in the code parsing the options so these will always appear in the output which could be surprising and it is not consistent with other similar areas which use info!

**Comment by jeremyandrews** [comment]
The things that are using `info!()` are debug logs that require setting `-v` to see.

There are things that are not debug logs, but fundamental to the load test that do intentionally do not require enabling debug logs to see. In particular: 1) when all Goose Users are up and running and the load test is generating maximum load, and 2) if we reset statistics after all users stop (which we do by default) because this info is permanently deleted at this point.

Currently there's no way to hide #1, and you can only disable #2 by setting `--no-reset-stats`. If this is somehow problematic, perhaps we could consider a `--quiet` or `--silent` flag which prevents any/all output (essentially silencing the above two outputs)?

**Comment by JordiPolo** [comment]
Yeah, unless I really want control and do not print anything unless I do it by myself. I think that's the most flexible for any use case.

**Pull request closed without merging**
